language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install cython pytest
  - cd dot && ./build-module.sh && cd ..
  - cd multiply && ./build-module.sh && cd ..
script:
  - cd dot
  - py.test
  - cd ../multiply
  - py.test
