language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pushd hello-world && pip install cython pytest && ./build-module.sh && popd
  - pushd dot && pip install cython pytest && ./build-module.sh && popd
script:
  - pushd hello-world && py.test && popd
  - pushd dot && py.test && popd
