language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip
install:
  - cd hello-world && pip install cython pytest && ./build-module.sh && cd ..
  - cd dot && pip install cython pytest && ./build-module.sh && cd ..
script:
  - cd hello-world && py.test && cd ..
  - cd dot && py.test && cd ..
