language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pushd hello-world && pip install cython pytest && popd
script:
  - pushd hello-world && py.test --cov-report term-missing --cov app -v
